// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vpganqviwrtmnrfvrrrx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZwZ2FucXZpd3J0bW5yZnZycnJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzgwNzQxOTYsImV4cCI6MjA5MzY1MDE5Nn0.x3iT4-Mji7FH1FjGzi0x2hHqeTjE5ZgyegHugL96bAA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});